name: Notify IndexNow after Vercel Deployment

on:
  push:
    branches:
      - main  # or your production branch

jobs:
  indexnow-ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run IndexNow Ping Script
        run: node scripts/indexnow.js
        env:
          NODE_OPTIONS: "--experimental-fetch"
